version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_DATABASE: cosmos-odyssey
    ports:
      - "27017:27017"
    networks:
      - rrnet

  # cosmos-odyssey-backend:
  #   container_name: cosmos-odyssey-backend
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile
  #   environment:
  #     PORT: 3000
  #     MONGODB_CONNECTION_STRING: mongodb://mongo:27017/cosmos-odyssey
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - rrnet

networks:
  rrnet:
    driver: bridge